title: Vol Cap Player
description: Volumetric Capture Video Player for Unity and Unreal Engine Documentation
theme: just-the-docs

url: https://DefkalionPap.github.io/Volumetric-Capture-Video-Player

aux_links:
  GitHub: https://github.com/DefkalionPap/Volumetric-Capture-Video-Player
