title: Volumetric Capture Video Player
description: Volumetric Capture Video Player for Unity and Unreal Engine Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/DefkalionPap/Volumetric-Capture-Video-Player
